export { MeusObjetivosPage } from './visualizar-objetivos/meus-objetivos'
export { DetalheObjetivoPage } from './visualizar-objetivos/detalhe-objetivo'
export { ObjetivosCompartilhadosPage } from './visualizar-objetivos/objetivos-compartilhados'
export { LoginPage } from './login'
export { ProjetoPage } from './projeto'
export { InvitePage } from './invite'